#---------------------------
# 全局
#---------------------------

# 用于浏览器标签的图标
favicon:
# 用于苹果设备的图标
apple_touch_icon:
# 浏览器标签页中的标题分隔符，效果：文章名 - 站点名
tab_title_separator: " - "
# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
force_https: true
# 代码块的增强配置
code:
  # 是否开启复制代码的按钮
  copy_btn: true
  # 代码语言
  language:
    enable: true
    default: "TEXT"
  # 代码高亮
  highlight:
    enable: true
    # 代码块是否显示行号
    line_number: true
    # 实现高亮的库，对应下面的设置
    # Options: highlightjs | prismjs
    lib: "prismjs"
    highlightjs:
      # 在链接中挑选 style 填入
      # See: https://highlightjs.org/demo/
      style: "github gist"
      style_dark: "dark"
    prismjs:
      # 在下方链接页面右侧的圆形按钮挑选 style 填入，也可以直接填入 css 链接
      # See: https://prismjs.com/
      style: "default"
      style_dark: "tomorrow night"
      # 设为 true 高亮将本地静态生成（但只支持部分 prismjs 插件），
      # 设为 false 高亮将在浏览器通过 js 生成
      preprocess: true
# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true
    # 打印速度，数字越大越慢
    typeSpeed: 70
    # 游标字符
    cursorChar: "_"
    # 是否循环播放效果
    loop: false
    # 在指定页面开启，不填则在所有页面开启
    # Options: home | post | tag | category | about | links | page | 404
    scope: []
  # 为文章内容中的标题添加锚图标
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    # Options: left | right
    placement: left
    # Options: hover | always
    visible: hover
    # Options: § | # | ❡
    icon: "#"
  # 加载进度条
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    # See: https://github.com/rstacruz/nprogress
    options: { showSpinner: false, trickleSpeed: 100 }
# 主题暗色模式，开启后菜单中会出现切换按钮，用户浏览器会存储切换选项，
# 并且会遵循 prefers-color-scheme 自动切换
dark_mode:
  enable: true
  # 默认的选项（当用户手动切换后则不再按照默认模式），
  # 选择 `auto` 会优先遵循 prefers-color-scheme，
  # 其次按用户本地时间 18 点到次日 6 点之间进入暗色模式
  # Options: auto | light | dark
  default: auto

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  body_bg_color: "#eee"
  # 暗色模式下的 body 背景色，下同
  body_bg_color_dark: "#181c27"
  # 顶部菜单背景色
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"
  # 顶部菜单字体色
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  # 副标题字体色
  subtitle_color: "#fff"
  subtitle_color_dark: "#d0d0d0"
  # 全局字体色
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"
  # 全局次级字体色（摘要、简介等位置）
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"
  # 主面板背景色
  board_color: "#fff"
  board_color_dark: "#252d38"
  # 文章正文字体色
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"
  # 文章正文字体色（h1 h2 h3...）
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"
  # 文章超链接字体色
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  # 超链接悬浮时字体色
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  # 超链接悬浮背景色
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"
  # 分隔线和表格边线的颜色
  line_color: "#eaecef"
  line_color_dark: "#435266"
  # 滚动条颜色
  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  # 滚动条悬浮颜色
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
  # 按钮背景色
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  # 按钮悬浮背景色
  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"
# 主题字体配置
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%
# 指定自定义 .js 文件路径，支持列表；
# 路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js
custom_js:
# 指定自定义 .css 文件路径，用法和 custom_js 相同
custom_css:
# 网页访问统计
web_analytics:
  enable: true
  # 遵循访客浏览器"请勿追踪"的设置，如果开启则不统计其访问
  # See: https://www.w3.org/TR/tracking-dnt/
  follow_dnt: true
  # 百度统计的 Key，值需要获取下方链接中 `hm.js?` 后边的字符串
  # See: https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376
  baidu:
  # Google Analytics 4 的媒体资源 ID
  # See: https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article
  google:
    measurement_id:
  # 腾讯统计的 H5 App ID，开启高级功能才有cid
  # See: https://mta.qq.com/h5/manage/ctr_app_manage
  tencent:
    sid:
    cid:
  # LeanCloud 计数统计，可用于 PV UV 展示，如果 `web_analytics: enable` 没有开启，
  # PV UV 展示只会查询不会增加
  leancloud:
    app_id:
    app_key:
    # REST API 服务器地址，国际版不填
    server_url:
    # 统计页面时获取路径的属性
    path: window.location.pathname
    # 开启后不统计本地路径( localhost 与 127.0.0.1 )
    ignore_local: false
  # Umami Analytics，仅支持自部署。如果要展示 PV UV 需要填写所有配置项，
  # 否则只填写 `src` 和 `website_id` 即可
  # See: https://umami.is/docs
  umami:
    # umami js 文件地址，需要在 umami 后台创建站点后获取
    src:
    # umami 的 website id，需要在 umami 后台创建站点后获取
    website_id:
    # 如果你只想统计特定的域名可以填入此字段，多个域名通过逗号分隔，这可以避免统计 localhost。
    domains:
    # 用于统计 PV UV 的开始时间，格式为 "YYYY-MM-DD"
    start_time: 2024-01-01
    # 新建一个 umami viewOnly 用户，然后通过 login api 获取该用户 token
    token:
    # 填写 umami 部署的服务器地址，如 "https://umami.example.com"
    api_server:
# Canonical 用于向 Google 搜索指定规范网址，开启前确保 hexo _config.yml
# 中配置 `url: http://yourdomain.com`
# See: https://support.google.com/webmasters/answer/139066
canonical:
  enable: false
# 对页面中的图片和评论插件进行懒加载处理，可见范围外的元素不会提前加载
lazyload:
  enable: true
  # 加载时的占位图片
  loading_img: /img/loading.gif
  # 开启后懒加载仅在文章页生效，如果自定义页面需要使用，可以在 Front-matter 里指定 `lazyload: true`
  onlypost: false
  # 触发加载的偏移倍数，基数是视窗高度，可根据部署环境的请求速度调节
  offset_factor: 2
# 图标库，包含了大量社交类图标，主题依赖的不包含在内，因此可自行修改，
# 详见 https://hexo.fluid-dev.com/docs/icon/
iconfont: //at.alicdn.com/t/c/font_1736178_k526ubmyhba.css

#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  blog_title: "道一开源日记"
  # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
  ground_glass:
    enable: true
    # 模糊像素，只能为数字，数字越大模糊度越高
    px: 3
    # 不透明度，数字越大透明度越低，注意透明过度可能看不清菜单字体
    # available: 0 - 1.0
    alpha: 0.7
  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，
  # 如不存在关联则显示key本身的值；icon是 css class，可以省略；增加 name 可以强制显示指定名称
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    #- { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# 搜索功能，基于 hexo-generator-search 插件，若已安装其他搜索插件请关闭此功能，以避免生成多余的索引文件
search:
  enable: true
  # 搜索索引文件的路径，可以是相对路径或外站的绝对路径
  path: /local-search.xml
  # 文件生成在本地的位置，必须是相对路径
  generate_path: /local-search.xml
  # 搜索的范围
  # Options: post | page | all
  field: post
  # 搜索是否扫描正文
  content: true
# 首屏图片的相关配置
banner:
  # 视差滚动，图片与板块会随着屏幕滚动产生视差效果
  parallax: true
  # 图片最小的宽高比，以免图片两边被过度裁剪，适用于移动端竖屏时，如需关闭设为 0
  width_height_ratio: 1.0
# 向下滚动的箭头
scroll_down_arrow:
  enable: true
  # 头图高度不小于指定比例，才显示箭头
  # Available: 0 - 100
  banner_height_limit: 80
  # 翻页后自动滚动
  scroll_after_turning_page: true
# 向顶部滚动的箭头
scroll_top_arrow:
  enable: true
# Open Graph metadata
# See: https://hexo.io/docs/helpers.html#open-graph
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 页脚第一行文字的 HTML，建议保留 Fluid 的链接，用于向更多人推广本主题
  content: ''
  # 展示网站的 PV、UV 统计数
  statistics:
    enable: true
    # 统计数据来源，使用 leancloud, umami 需要设置 `web_analytics` 中对应的参数；使用 busuanzi 不需要额外设置，但是有时不稳定，另外本地运行时 busuanzi 显示统计数据很大属于正常现象，部署后会正常
    # Options: busuanzi | leancloud | umami
    source: "busuanzi"
  # 国内大陆服务器的备案信息
  beian:
    enable: true
    # ICP证号
    icp_text: 滇ICP备2023006063号-1
    # 公安备案号，不填则只显示ICP
    police_text: 滇公网安备 53011202001306号
    # 公安备案的编号，用于URL跳转查询
    police_code: 53011202001306
    # 公安备案的图片. 为空时不显示备案图片
    police_icon: /img/police_beian.png


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/default.png
  # 头图高度，屏幕百分比
  # Available: 0 - 100
  banner_img_height: 100
  # 头图黑色蒙版的不透明度，available: 0 - 1.0，1 是完全不透明
  # Available: 0 - 1.0
  banner_mask_alpha: 0.3
  # 首页副标题的独立设置
  slogan:
    enable: true
    # 为空则按 hexo config.subtitle 显示
    text: "道可道,非常道也;名可名,非常名也;"
    # 通过 API 接口作为首页副标题的内容，必须返回的是 JSON 格式，
    # 如果请求失败则按 text 字段显示，该功能必须先开启 typing 打字机功能
    api:
      enable: false
      # 请求地址
      url: ""
      # 请求方法
      # Available: GET | POST | PUT
      method: "GET"
      # 请求头
      # Request headers
      headers: {}
      # 从请求结果获取字符串的取值字段，最终必须是一个字符串，
      # 例如返回结果为 {"data": {"author": "fluid", "content": "An elegant theme"}},
      # 则取值字段为 ['data', 'content']；如果返回是列表则自动选择第一项
      keys: []
  # 自动截取文章摘要
  auto_excerpt:
    enable: true
  # 打开文章的标签方式
  # Available: _blank | _self
  post_url_target: _self
  # 是否显示文章信息（时间、分类、标签）
  post_meta:
    date: true
    category: true
    tag: true
  # 文章通过 sticky 排序后，在首页文章标题前显示图标
  post_sticky:
    enable: true
    icon: "iconfont icon-top"

#---------------------------
# 文章页
#---------------------------
post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  # 文章在首页的默认封面图，当没有指定 index_img 时会使用该图片，若两者都为空则不显示任何图片
  default_index_img:
  # 文章标题下方的元信息
  meta:
    # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
    author:
      enable: false
    # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
    date:
      enable: true
      # 格式参照 ISO-8601 日期格式化
      # See: http://momentjs.cn/docs/#/parsing/string-format/
      format: "LL a"
    # 字数统计
    wordcount:
      enable: true
    # 估计阅读全文需要的时长
    min2read:
      enable: true
      # 每个字词的长度，建议：中文≈2，英文≈5，中英混合可自行调节
      awl: 2
      # 每分钟阅读字数，如果大部分是技术文章可适度调低
      wpm: 60
    # 浏览量计数
    views:
      enable: true
      # 统计数据来源
      # Options: busuanzi | leancloud | umami
      source: "busuanzi"
  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，
  # 可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  updated:
    enable: true
    # 格式参照 ISO-8601 日期格式化
    # See: http://momentjs.cn/docs/#/parsing/string-format/
    date_format: "LL a"
    # 是否使用相对时间表示，比如："3 天前"
    relative: true
    # 提示标签类型
    # Options: default | primary | info | success | warning | danger | light
    note_class: info
  # 侧边栏展示当前分类下的文章
  category_bar:
    enable: true
    # 开启后，只有在文章 Front-matter 里指定 `category_bar: true` 才会展示分类，
    # 也可以通过 `category_bar: ["分类A"]` 来指定分类
    specific: true
    # 置于板块的左侧或右侧
    # Options: left | right
    placement: left
    # 文章的排序字段，前面带减号是倒序，不带减号是正序
    # Options: date | title | or other field of front-matter
    post_order_by: "date"
    # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
    post_limit: 0
  # 侧边栏展示文章目录
  toc:
    enable: true
    # 置于板块的左侧或右侧
    # Options: left | right
    placement: right
    # 目录会选择这些节点作为标题
    headingSelector: "h1,h2,h3,h4,h5,h6"
    # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在下级标题则默认展开
    collapseDepth: 0
  # 版权声明，会显示在每篇文章的结尾
  copyright:
    enable: true
    # CreativeCommons license
    # See: https://creativecommons.org/share-your-work/cclicenses/
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND | ZERO
    license: 'BY-NC-SA'
    # 显示作者
    author:
      enable: true
    # 显示发布日期
    post_date:
      enable: true
      format: "LL"
    # 显示更新日期
    update_date:
      enable: false
      format: "LL"
  # 文章底部上一篇下一篇功能
  prev_next:
    enable: true
  # 文章图片标题
  image_caption:
    enable: true
  # 文章图片可点击放大
  image_zoom:
    enable: true
    # 放大后图片链接替换规则，可用于将压缩图片链接替换为原图片链接，如 ['-slim', '']
    # 是将链接中 `-slim` 移除；如果想使用正则请使用 `re:` 前缀，
    # 如 ['re:\\d{3,4}\\/\\d{3,4}\\/', '']
    img_url_replace: ['', '']
  # 脚注语法，会在文章底部生成脚注，如果 Markdown 渲染器本身支持，则建议关闭，否则可能会冲突
  footnote:
    enable: true
    # 脚注的节标题，也可以在 front-matter 中通过 `footnote: <h2>Reference</h2>` 这种形式修改单独页面的 header
    header: ''
  # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，
  # 具体请见：https://hexo.fluid-dev.com/docs/guide/##latex-数学公式
  math:
    # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    enable: false
    # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，
    # 以便在页面不包含公式时提高加载速度
    specific: false
    # Options: mathjax | katex
    engine: mathjax
  # 流程图，基于 mermaid-js，
  # 具体请见：https://hexo.fluid-dev.com/docs/guide/#mermaid-流程图
  mermaid:
    # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `mermaid: true`
    enable: false
    # 开启后，只有在文章 Front-matter 里指定 `mermaid: true` 才会在文章页启动公式转换，
    # 以便在页面不包含公式时提高加载速度
    specific: false
    # See: http://mermaid-js.github.io/mermaid/
    options: { theme: 'default' }
  # 评论插件
  comments:
    enable: false

#---------------------------
# 归档页
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# 分类页
#---------------------------
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # 分类的排序字段，前面带减号是倒序，不带减号是正序
  # Options: length | name
  order_by: "-length"
  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  collapse_depth: 0
  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"
  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
  post_limit: 10

#---------------------------
# 标签页
#---------------------------
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

#---------------------------
# 关于页
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /images/links_avatar_yangxj96.jpg
  name: "道一哥哥"
  intro: "道可道,非常道也;名可名,非常名也;"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，
  # `class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/yangxj96", tip: "GitHub" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/images/wechat-pay.jpg" }

#---------------------------
# 自定义页
# 通过 hexo new page 命令创建的页面
#---------------------------
page:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3

#---------------------------
# 404页
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  # 重定向到首页的延迟(毫秒)
  redirect_delay: 5000

#---------------------------
# 友链页
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # 友链的成员项
  items:
    - {
      title: "道一哥哥",
      intro: "CSDN",
      link: "https://blog.csdn.net/qq_37274323",
      avatar: "/images/links_avatar_yangxj96.jpg"
    }
    - {
      title: "心随梦舞-祥",
      intro: "CSDN",
      link: "https://blog.csdn.net/weixin_42139418",
      avatar: "/images/links_avatar_wuxiang.jpg"
    }
  # 当成员头像加载失败时，替换为指定图片
  onerror_avatar: /img/avatar.png
  # 友链下方自定义区域，支持 HTML，可插入例如申请友链的文字
  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'
  # 评论插件
  comments:
    enable: false
    # 指定的插件，需要同时设置对应插件的必要参数
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus | discuss
    type: disqus

#---------------------------
# 以下是配置 JS CSS 等静态资源的 URL 前缀，可以自定义成 CDN 地址，
# 如果需要修改，最好使用与默认配置相同的版本，以避免潜在的问题，
# 如果你不知道如何设置，请不要做任何改动
#---------------------------

static_prefix:
  # 内部静态
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/5.0.0/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://registry.npmmirror.com/@waline/client/2.15.8/files/dist/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  discuss: https://lib.baomitu.com/discuss/1.2.1/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/